services:
  backend:
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.devgon.site
      - LETSENCRYPT_HOST=api.devgon.site
      - LETSENCRYPT_EMAIL=devgonteam@gmail.com
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=devgon.site
      - LETSENCRYPT_HOST=devgon.site
      - LETSENCRYPT_EMAIL=devgonteam@gmail.com
    networks:
      - app-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=devgonteam@gmail.com
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge